### ISSUE TITLE
No such group or event: TermOpen * setlocal nonumber norelativenumber

### ISSUE THREAD

**Issue by rkenzhebekov** [Arkham/vimfiles#2]
Hi Ju,

I wanted to try your vim setup but got the following error:
```
vagrant@box:~/.vim$ rake
mkdir -p plugged
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 74467  100 74467    0     0   233k      0 --:--:-- --:--:-- --:--:--  233k
mkdir -p _backup
mkdir -p _temp
ln -s .vim/vimrc /home/vagrant/.vimrc
vim
Error detected while processing /home/vagrant/.vimrc:
line  185:
E216: No such group or event: TermOpen * setlocal nonumber norelativenumber
line  299:
E254: Cannot allocate color 124
Press ENTER or type command to continue
```

I tried on: MacOS Mojave 10.14.6 vim 8.1.1700 and Ubuntu 18.04

**Comment by Arkham** [comment]
Hey @rkenzhebekov, I've only seen this now! Were you able to fix the issue?

**Comment by rkenzhebekov** [comment]
Hello @Arkham,

Yes, I think it was related to the nvim not being available on my PC. I was able to use your vimrc after this change https://github.com/rkenzhebekov/vimfiles/commit/d956253ea81c7fdf6f5bd552188394de40e0e22c

However, I couldn't figure out how to convert '|>' to the pretty symbol in elixir file similar to how it is shown on your screenshot 😄 Maybe, I'm still missing something. 

If you think my change is useful I can open a PR to your branch or feel free to copy to your branch. 

Thank you for sharing your vim setup!!!

**Comment by Arkham** [comment]
Oh thank you, I will copy off the changes in your branch :)

The nice '|>' symbol comes from this special font (https://github.com/tonsky/FiraCode) which has ligature support.

Have a nice day!

**Comment by Arkham** [comment]
All fixed now, going to close this!
